"""empty message

Revision ID: 003b2f921870
Revises: dfc69a0b2213
Create Date: 2024-06-12 20:40:41.962491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '003b2f921870'
down_revision: Union[str, None] = 'dfc69a0b2213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'tools',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.Enum('Wiki_Retriever_LangChain', 'Search_File', 'Read_File', 'Python_Interpreter', 'Calculator', 'Tavily_Internet_Search', name='toolname', native_enum=False)),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'tools',
               existing_type=postgresql.ARRAY(sa.Enum('Wiki_Retriever_LangChain', 'Search_File', 'Read_File', 'Python_Interpreter', 'Calculator', 'Tavily_Internet_Search', name='toolname', native_enum=False)),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False)
    # ### end Alembic commands ###
