"""empty message

Revision ID: 06687ce9ea3b
Revises: 038075cd8530
Create Date: 2024-06-25 17:40:11.030143

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06687ce9ea3b"
down_revision: Union[str, None] = "038075cd8530"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("tool_plan", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "tool_plan")
    # ### end Alembic commands ###
