"""empty message

Revision ID: 11d3e318274c
Revises: 3d60aa423ec6
Create Date: 2024-06-27 21:11:23.900678

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11d3e318274c"
down_revision: Union[str, None] = "3d60aa423ec6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "_user_agent_tool_name_uc", "agent_tool_metadata", type_="unique"
    )
    op.create_unique_constraint(
        "_user_agent_tool_name_type_uc",
        "agent_tool_metadata",
        ["user_id", "agent_id", "tool_name", "type"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "_user_agent_tool_name_type_uc", "agent_tool_metadata", type_="unique"
    )
    op.create_unique_constraint(
        "_user_agent_tool_name_uc",
        "agent_tool_metadata",
        ["user_id", "agent_id", "tool_name"],
    )
    # ### end Alembic commands ###
