"""Add user tools

Revision ID: 67f8e730f578
Revises: a76ebb869eb8
Create Date: 2024-08-12 15:28:57.120948

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67f8e730f578"
down_revision: Union[str, None] = "a76ebb869eb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("tools", sa.JSON(), server_default="[]", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "tools")
    # ### end Alembic commands ###
