"""Add is_private column to agents

Revision ID: 279a4298107b
Revises: 117f0d9b1d3d
Create Date: 2024-08-07 14:21:16.814206

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "279a4298107b"
down_revision: Union[str, None] = "117f0d9b1d3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("is_private", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "is_private")
    # ### end Alembic commands ###
