"""Add is_private column to agents

Revision ID: b721b6384459
Revises: 7d85cfb9ec27
Create Date: 2024-08-02 20:57:46.182465

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b721b6384459"
down_revision: Union[str, None] = "7d85cfb9ec27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("is_private", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "is_private")
    # ### end Alembic commands ###
