"""Add agent_id foreign key to snapshots

Revision ID: c3c3d4f96f5a
Revises: 71d7b35c8a44
Create Date: 2024-08-09 11:07:57.811281

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3c3d4f96f5a"
down_revision: Union[str, None] = "71d7b35c8a44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("snapshots", sa.Column("agent_id", sa.String(), nullable=True))
    op.create_index("snapshot_agent_id", "snapshots", ["agent_id"], unique=False)
    op.create_foreign_key(
        None, "snapshots", "agents", ["agent_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "snapshots", type_="foreignkey")
    op.drop_index("snapshot_agent_id", table_name="snapshots")
    op.drop_column("snapshots", "agent_id")
    # ### end Alembic commands ###
