"""

Revision ID: 5ef133f87ccb
Revises: 08bcb9a24d9b
Create Date: 2024-08-22 16:58:54.903120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef133f87ccb'
down_revision: Union[str, None] = '08bcb9a24d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('carbon_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'carbon_id')
    # ### end Alembic commands ###
