"""empty message

Revision ID: 2b4c3983d9bf
Revises: f9fb258c0c68
Create Date: 2024-07-31 13:32:57.861913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b4c3983d9bf'
down_revision: Union[str, None] = 'f9fb258c0c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active')
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###
