"""empty message

Revision ID: 36c525f80336
Revises: 6d9352fcfacb
Create Date: 2024-06-14 20:39:58.961391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c525f80336'
down_revision: Union[str, None] = '6d9352fcfacb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'model',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('agents', 'deployment',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'deployment',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('agents', 'model',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
    # ### end Alembic commands ###
