"""empty message

Revision ID: 3a2c90817791
Revises: f7ad93967810
Create Date: 2024-07-09 15:04:42.242390

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a2c90817791"
down_revision: Union[str, None] = "f7ad93967810"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("documents_user_id_fkey", "documents", type_="foreignkey")
    op.drop_constraint("files_conversation_id_fkey", "files", type_="foreignkey")
    op.drop_constraint(
        "documents_conversation_id_fkey", "documents", type_="foreignkey"
    )
    op.drop_constraint("files_user_id_fkey", "files", type_="foreignkey")
    op.drop_constraint("messages_conversation_id_fkey", "messages", type_="foreignkey")
    op.drop_constraint("messages_user_id_fkey", "messages", type_="foreignkey")
    op.drop_constraint("snapshots_user_id_fkey", "snapshots", type_="foreignkey")
    op.drop_constraint(
        "snapshots_conversation_id_fkey", "snapshots", type_="foreignkey"
    )
    op.drop_constraint("conversations_pkey", "conversations", type_="primary")

    op.create_unique_constraint(
        "conversation_id_user_id", "conversations", ["id", "user_id"]
    )
    op.create_primary_key("conversation_pkey", "conversations", ["id", "user_id"])
    op.create_index(
        "conversation_user_id_index", "conversations", ["id", "user_id"], unique=True
    )
    op.create_foreign_key(
        "document_conversation_id_user_id_fkey",
        "documents",
        "conversations",
        ["conversation_id", "user_id"],
        ["id", "user_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "file_conversation_id_user_id_fkey",
        "files",
        "conversations",
        ["conversation_id", "user_id"],
        ["id", "user_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "message_conversation_id_user_id_fkey",
        "messages",
        "conversations",
        ["conversation_id", "user_id"],
        ["id", "user_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "snapshot_conversation_id_user_id_fkey",
        "snapshots",
        "conversations",
        ["conversation_id", "user_id"],
        ["id", "user_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "snapshot_conversation_id_user_id_fkey", "snapshots", type_="foreignkey"
    )
    op.drop_constraint(
        "message_conversation_id_user_id_fkey", "messages", type_="foreignkey"
    )
    op.drop_constraint("file_conversation_id_user_id_fkey", "files", type_="foreignkey")
    op.drop_constraint(
        "document_conversation_id_user_id_fkey", "documents", type_="foreignkey"
    )
    op.drop_index("conversation_user_id_index", table_name="conversations")
    op.drop_constraint("conversation_pkey", "conversations", type_="primary")
    op.drop_constraint("conversation_id_user_id", "conversations", type_="unique")

    op.create_primary_key("conversations_pkey", "conversations", ["id"])
    op.create_foreign_key(
        "snapshots_conversation_id_fkey",
        "snapshots",
        "conversations",
        ["conversation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "snapshots_user_id_fkey",
        "snapshots",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "messages_user_id_fkey",
        "messages",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "messages_conversation_id_fkey",
        "messages",
        "conversations",
        ["conversation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "files_user_id_fkey", "files", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "documents_conversation_id_fkey",
        "documents",
        "conversations",
        ["conversation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "files_conversation_id_fkey",
        "files",
        "conversations",
        ["conversation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "documents_user_id_fkey",
        "documents",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
