"""empty message

Revision ID: 3db4a6321b7a
Revises: ed17f144f4bf
Create Date: 2024-07-16 00:17:46.627947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db4a6321b7a'
down_revision: Union[str, None] = 'ed17f144f4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deployment_class_name', sa.Text(), nullable=True),
    sa.Column('is_community', sa.Boolean(), nullable=False),
    sa.Column('default_deployment_config', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='deployment_name_uc')
    )
    op.create_table('models',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('cohere_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deployment_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_deployment_model',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('deployment_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('deployment_config', sa.JSON(), nullable=True),
    sa.Column('is_default_deployment', sa.Boolean(), nullable=False),
    sa.Column('is_default_model', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deployment_id', 'agent_id', 'model_id', name='deployment_agent_model_uc')
    )
    op.alter_column('agents', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('agents', 'model')
    op.drop_column('agents', 'deployment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('deployment', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('model', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('agents', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('agent_deployment_model')
    op.drop_table('models')
    op.drop_table('deployments')
    # ### end Alembic commands ###
