"""empty message

Revision ID: 40e6b2b2282c
Revises: ed17f144f4bf
Create Date: 2024-07-22 22:18:29.248857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e6b2b2282c'
down_revision: Union[str, None] = 'ed17f144f4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist', sa.Column('effective_at', sa.DateTime(), nullable=False))
    op.add_column('blacklist', sa.Column('expires_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blacklist', 'expires_at')
    op.drop_column('blacklist', 'effective_at')
    # ### end Alembic commands ###
