"""empty message

Revision ID: 4e0f91fadd2c
Revises: 613de756f789
Create Date: 2024-08-02 13:30:35.940412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e0f91fadd2c'
down_revision: Union[str, None] = '613de756f789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_group_user', 'user_group', ['group_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_group_user', 'user_group', type_='unique')
    # ### end Alembic commands ###
