"""empty message

Revision ID: 51fa728b62a9
Revises: 16e91cfbdf35
Create Date: 2024-06-26 16:06:00.995142

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51fa728b62a9"
down_revision: Union[str, None] = "16e91cfbdf35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("snapshots", sa.Column("snapshot", sa.JSON(), nullable=False))
    op.drop_column("snapshots", "title")
    op.drop_column("snapshots", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "snapshots",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "snapshots",
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("snapshots", "snapshot")
    # ### end Alembic commands ###
