"""empty message

Revision ID: 5a743afe3cf1
Revises: f5819b10ef2a
Create Date: 2024-06-07 21:51:03.915435

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a743afe3cf1"
down_revision: Union[str, None] = "f5819b10ef2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklist",
        sa.Column("token_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("blacklist_token_id", "blacklist", ["token_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("blacklist_token_id", table_name="blacklist")
    op.drop_table("blacklist")
    # ### end Alembic commands ###
