"""empty message

Revision ID: 5c3adc3d6a0a
Revises: ed17f144f4bf
Create Date: 2024-07-25 16:13:07.522825

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c3adc3d6a0a"
down_revision: Union[str, None] = "ed17f144f4bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "conversations", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "conversations", type_="unique")
    # ### end Alembic commands ###
