"""empty message

Revision ID: 613de756f789
Revises: 9cd2d3c0fcb6
Create Date: 2024-08-02 10:41:26.586621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '613de756f789'
down_revision: Union[str, None] = '9cd2d3c0fcb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_group', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_group', sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
