"""empty message

Revision ID: 6d9352fcfacb
Revises: 922e874930bf
Create Date: 2024-06-14 17:54:24.360154

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6d9352fcfacb"
down_revision: Union[str, None] = "922e874930bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agents",
        "tools",
        existing_type=postgresql.ARRAY(sa.VARCHAR(length=24)),
        type_=postgresql.ARRAY(sa.Text()),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agents",
        "tools",
        existing_type=postgresql.ARRAY(sa.Text()),
        type_=postgresql.ARRAY(sa.VARCHAR(length=24)),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
