"""empty message

Revision ID: 75ba36f86a00
Revises: 922e874930bf
Create Date: 2024-06-13 17:11:01.079714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ba36f86a00'
down_revision: Union[str, None] = '922e874930bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('agent_id', sa.String(), nullable=True))
    op.create_index('conversation_agent_id', 'conversations', ['agent_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index('conversation_agent_id', table_name='conversations')
    op.drop_column('conversations', 'agent_id')
    # ### end Alembic commands ###
