"""empty message

Revision ID: 807f7ce96e0d
Revises: ed17f144f4bf
Create Date: 2024-07-29 15:17:58.433386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807f7ce96e0d'
down_revision: Union[str, None] = 'ed17f144f4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_files',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('conversation_user_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id', 'conversation_user_id'], ['conversations.id', 'conversations.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'file_id', name='unique_conversation_file')
    )
    op.create_table('message_files',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'file_id', name='unique_message_file')
    )
    op.create_index('message_file_file_id', 'message_files', ['file_id'], unique=False)
    op.drop_index('file_conversation_id', table_name='files')
    op.drop_index('file_conversation_id_user_id', table_name='files')
    op.drop_index('file_message_id', table_name='files')
    op.drop_index('file_user_id', table_name='files')
    op.drop_constraint('files_message_id_fkey', 'files', type_='foreignkey')
    op.drop_constraint('file_conversation_id_user_id_fkey', 'files', type_='foreignkey')
    op.drop_column('files', 'message_id')
    op.drop_column('files', 'conversation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('conversation_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('file_conversation_id_user_id_fkey', 'files', 'conversations', ['conversation_id', 'user_id'], ['id', 'user_id'], ondelete='CASCADE')
    op.create_foreign_key('files_message_id_fkey', 'files', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_index('file_user_id', 'files', ['user_id'], unique=False)
    op.create_index('file_message_id', 'files', ['message_id'], unique=False)
    op.create_index('file_conversation_id_user_id', 'files', ['conversation_id', 'user_id'], unique=False)
    op.create_index('file_conversation_id', 'files', ['conversation_id'], unique=False)
    op.drop_index('message_file_file_id', table_name='message_files')
    op.drop_table('message_files')
    op.drop_table('conversation_files')
    # ### end Alembic commands ###
