"""empty message

Revision ID: 8353dff8a735
Revises: ee689d3849f6
Create Date: 2024-08-05 11:11:35.533866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8353dff8a735'
down_revision: Union[str, None] = 'ee689d3849f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_group', 'display')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_group', sa.Column('display', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
