"""empty message

Revision ID: 921186f281b7
Revises: 15bb10e272ff
Create Date: 2024-06-05 18:58:17.560063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921186f281b7'
down_revision: Union[str, None] = '15bb10e272ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_name_version_uc', 'agents', ['name', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_name_version_uc', 'agents', type_='unique')
    # ### end Alembic commands ###
