"""empty message

Revision ID: 998b82dfd78f
Revises: 7d85cfb9ec27
Create Date: 2024-08-01 17:22:51.494105

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "998b82dfd78f"
down_revision: Union[str, None] = "7d85cfb9ec27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("is_private", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "is_private")
    # ### end Alembic commands ###
