"""empty message

Revision ID: 9cd2d3c0fcb6
Revises: f2dba70ece12
Create Date: 2024-08-01 19:23:50.778554

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9cd2d3c0fcb6"
down_revision: Union[str, None] = "f2dba70ece12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("groups_external_id_key", "groups", type_="unique")
    op.drop_column("groups", "meta")
    op.drop_column("groups", "external_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups",
        sa.Column("external_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "groups", sa.Column("meta", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_unique_constraint("groups_external_id_key", "groups", ["external_id"])
    # ### end Alembic commands ###
