"""empty message

Revision ID: a42ebaf2503a
Revises: f02093586f37
Create Date: 2024-06-27 16:17:00.997809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a42ebaf2503a'
down_revision: Union[str, None] = 'f02093586f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_tool_metadata', 'artifact_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_tool_metadata', 'artifact_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
