"""empty message

Revision ID: ab2ba1fbe206
Revises: 51fa728b62a9
Create Date: 2024-06-26 16:14:12.542692

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab2ba1fbe206"
down_revision: Union[str, None] = "51fa728b62a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("snapshot_links", sa.Column("user_id", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("snapshot_links", "user_id")
    # ### end Alembic commands ###
