"""empty message

Revision ID: b48775c797b2
Revises: 1ded6d9c8a14
Create Date: 2024-08-05 12:41:10.059021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48775c797b2'
down_revision: Union[str, None] = '1ded6d9c8a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_group', sa.Column('display', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_group', 'display')
    # ### end Alembic commands ###
