"""empty message

Revision ID: c3d2bca1d7e7
Revises: a42ebaf2503a
Create Date: 2024-06-27 17:05:28.935726

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c3d2bca1d7e7"
down_revision: Union[str, None] = "a42ebaf2503a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_tool_metadata",
        sa.Column("artifacts", postgresql.ARRAY(sa.Text()), nullable=True),
    )
    op.alter_column(
        "agent_tool_metadata",
        "user_id",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "agent_tool_metadata",
        "tool_name",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.drop_column("agent_tool_metadata", "artifact_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_tool_metadata",
        sa.Column("artifact_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "agent_tool_metadata",
        "tool_name",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "agent_tool_metadata",
        "user_id",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("agent_tool_metadata", "artifacts")
    # ### end Alembic commands ###
