"""empty message

Revision ID: dfc69a0b2213
Revises: 21e6d6ddaaa2
Create Date: 2024-06-12 18:03:45.362347

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dfc69a0b2213"
down_revision: Union[str, None] = "21e6d6ddaaa2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agents", sa.Column("tools", postgresql.ARRAY(sa.Text()), nullable=False)
    )
    op.drop_column("agents", "tool")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agents",
        sa.Column(
            "tool", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("agents", "tools")
    # ### end Alembic commands ###
