"""empty message

Revision ID: e32e81802150
Revises: a6af4df00781
Create Date: 2024-06-27 17:23:42.997565

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e32e81802150"
down_revision: Union[str, None] = "a6af4df00781"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_tool_metadata",
        sa.Column("google_drive_file_ids", postgresql.ARRAY(sa.Text()), nullable=True),
    )
    op.add_column(
        "agent_tool_metadata",
        sa.Column(
            "google_drive_folder_ids", postgresql.ARRAY(sa.Text()), nullable=True
        ),
    )
    op.drop_column("agent_tool_metadata", "artifacts")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_tool_metadata",
        sa.Column(
            "artifacts", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("agent_tool_metadata", "google_drive_folder_ids")
    op.drop_column("agent_tool_metadata", "google_drive_file_ids")
    # ### end Alembic commands ###
