"""empty message

Revision ID: ee689d3849f6
Revises: 4e0f91fadd2c
Create Date: 2024-08-05 10:49:25.306062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee689d3849f6'
down_revision: Union[str, None] = '4e0f91fadd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_group_user', 'user_group', type_='unique')
    op.drop_constraint('user_group_group_id_fkey', 'user_group', type_='foreignkey')
    op.drop_constraint('user_group_user_id_fkey', 'user_group', type_='foreignkey')
    op.create_foreign_key(None, 'user_group', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_group', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_group', type_='foreignkey')
    op.drop_constraint(None, 'user_group', type_='foreignkey')
    op.create_foreign_key('user_group_user_id_fkey', 'user_group', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_group_group_id_fkey', 'user_group', 'groups', ['group_id'], ['id'])
    op.create_unique_constraint('uix_group_user', 'user_group', ['group_id', 'user_id'])
    # ### end Alembic commands ###
