"""empty message

Revision ID: f2d4d096af73
Revises: a9b07acef4e8
Create Date: 2024-06-12 20:55:57.032465

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f2d4d096af73"
down_revision: Union[str, None] = "a9b07acef4e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agents",
        sa.Column(
            "tools",
            postgresql.ARRAY(
                sa.Enum(
                    "Wiki_Retriever_LangChain",
                    "Search_File",
                    "Read_File",
                    "Python_Interpreter",
                    "Calculator",
                    "Tavily_Internet_Search",
                    name="toolname",
                    native_enum=False,
                )
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "tools")
    # ### end Alembic commands ###
