"""empty message

Revision ID: f2dba70ece12
Revises: 2b4c3983d9bf
Create Date: 2024-08-01 18:30:21.863024

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2dba70ece12"
down_revision: Union[str, None] = "2b4c3983d9bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("external_id", sa.String(), nullable=True))
    op.add_column("groups", sa.Column("meta", sa.String(), nullable=True))
    op.alter_column("groups", "display_name", existing_type=sa.VARCHAR(), nullable=True)
    op.create_unique_constraint(None, "groups", ["external_id"])
    op.add_column("user_group", sa.Column("value", sa.String(), nullable=False))
    op.add_column("user_group", sa.Column("display", sa.String(), nullable=True))
    op.drop_constraint("user_group_user_id_fkey", "user_group", type_="foreignkey")
    op.drop_constraint("user_group_group_id_fkey", "user_group", type_="foreignkey")
    op.create_foreign_key(None, "user_group", "groups", ["group_id"], ["id"])
    op.create_foreign_key(None, "user_group", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_group", type_="foreignkey")
    op.drop_constraint(None, "user_group", type_="foreignkey")
    op.create_foreign_key(
        "user_group_group_id_fkey",
        "user_group",
        "groups",
        ["group_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "user_group_user_id_fkey",
        "user_group",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("user_group", "display")
    op.drop_column("user_group", "value")
    op.drop_constraint(None, "groups", type_="unique")
    op.alter_column(
        "groups", "display_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("groups", "meta")
    op.drop_column("groups", "external_id")
    # ### end Alembic commands ###
