"""empty message

Revision ID: f9fb258c0c68
Revises: 24bbe2401556
Create Date: 2024-07-31 11:01:56.504464

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9fb258c0c68"
down_revision: Union[str, None] = "24bbe2401556"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("external_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "external_id")
    # ### end Alembic commands ###
