name: Backend - Lint

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
      - name: Run lint checks
        uses: chartboost/ruff-action@v1
        with:
          src: './src/'
          version: 0.6.0
